import { FileText, Star, AlertTriangle, Clock } from "lucide-react";

export default function DashboardPage() {
  return (
    <div className="w-full min-h-screen space-y-10 ">
      {/* PAGE TITLE */}
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
        <p className="text-gray-500 mt-1">
          AI yordamida hujjatlarni boshqarish va tahlil qilish
        </p>
      </div>

      {/* STATS */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-8">
        <StatCard
          title="Documents Generated"
          value="24"
          icon={<FileText />}
          color="bg-indigo-600"
        />
        <StatCard
          title="Risks Detected"
          value="7"
          icon={<AlertTriangle />}
          color="bg-amber-500"
        />
        <StatCard
          title="Completed"
          value="18"
          icon={<Star />}
          color="bg-emerald-600"
        />
        <StatCard
          title="Pending"
          value="6"
          icon={<Clock />}
          color="bg-slate-700"
        />
      </div>

      {/* MAIN CONTENT */}
      <div className="grid grid-cols-12 gap-8">
        {/* MAIN */}
        <div className="col-span-12 xl:col-span-12 bg-white rounded-3xl p-8 shadow-sm">
          <h2 className="text-xl font-semibold text-gray-800 mb-6">
            Recent Documents
          </h2>

          <div className="space-y-4">
            {[
              "Rental Agreement",
              "Freelance Contract",
              "Employment Offer",
            ].map((doc, i) => (
              <div
                key={i}
                className="flex items-center justify-between p-4 rounded-xl hover:bg-gray-50 transition"
              >
                <div>
                  <p className="font-medium text-gray-800">{doc}</p>
                  <p className="text-sm text-gray-500">Generated by AI</p>
                </div>
                <span className="text-sm px-3 py-1 rounded-full bg-green-100 text-green-700">
                  Complete
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ---------------- COMPONENTS ---------------- */

function StatCard({
  title,
  value,
  icon,
  color,
}: {
  title: string;
  value: string;
  icon: React.ReactNode;
  color: string;
}) {
  return (
    <div className="bg-white rounded-3xl p-6 shadow-sm flex items-center gap-5">
      <div
        className={`w-14 h-14 ${color} text-white rounded-2xl flex items-center justify-center`}
      >
        {icon}
      </div>
      <div>
        <p className="text-sm text-gray-500">{title}</p>
        <p className="text-2xl font-bold text-gray-900">{value}</p>
      </div>
    </div>
  );
}

function ActionButton({ label }: { label: string }) {
  return (
    <button className="w-full py-4 rounded-xl bg-gray-50 hover:bg-indigo-50 hover:text-indigo-600 transition font-medium">
      {label}
    </button>
  );
}
